### ISSUE TITLE
c++中map的使用方式问题

### ISSUE THREAD

**Issue by voidii** [ShuaiHuang/shuaihuang.github.io#1]
```cpp
class Solution {
public:
    vector<int> twoSum(vector<int> &numbers, int target)
{
    //Key is the number and value is its index in the vector.
	unordered_map<int, int> hash;
	vector<int> result;
	for (int i = 0; i < numbers.size(); i++) {
		int numberToFind = target - numbers[i];

            //if numberToFind is found in map, return them
		if (hash.find(numberToFind) != hash.end()) {
                    //+1 because indices are NOT zero based
			result.push_back(hash[numberToFind]);
			result.push_back(i);			
			return result;
		}

            //number was not found. Put it in the map.
		hash[numbers[i]] = i;
	}
	return result;
}
};
```
这段代码中，`hash[number[i]] = i` 这个操作没有看懂，这难道不是把这个loop循环的次数储存在了map中吗？我很迷惑

**Comment by voidii** [comment]
```class Solution {
public:
    vector<int> twoSum(vector<int> &numbers, int target)
{
    //Key is the number and value is its index in the vector.
	unordered_map<int, int> hash;
	vector<int> result;
	for (int i = 0; i < numbers.size(); i++) {
		int numberToFind = target - numbers[i];

            //if numberToFind is found in map, return them
		if (hash.find(numberToFind) != hash.end()) {
                    //+1 because indices are NOT zero based
			result.push_back(hash[numberToFind]);
			result.push_back(i);			
			return result;
		}

            //number was not found. Put it in the map.
		hash[numbers[i]] = i;
	}
	return result;
}
};```

**Comment by ShuaiHuang** [comment]
> ```c++
> class Solution {
> public:
>     vector<int> twoSum(vector<int> &numbers, int target)
> {
>     //Key is the number and value is its index in the vector.
> 	unordered_map<int, int> hash;
> 	vector<int> result;
> 	for (int i = 0; i < numbers.size(); i++) {
> 		int numberToFind = target - numbers[i];
> 
>             //if numberToFind is found in map, return them
> 		if (hash.find(numberToFind) != hash.end()) {
>                     //+1 because indices are NOT zero based
> 			result.push_back(hash[numberToFind]);
> 			result.push_back(i);			
> 			return result;
> 		}
> 
>             //number was not found. Put it in the map.
> 		hash[numbers[i]] = i;
> 	}
> 	return result;
> }
> };
> ```
> 
> 这段代码中，`hash[number[i]] = i` 这个操作没有看懂，这难道不是把这个loop循环的次数储存在了map中吗？我很迷惑

unordered_map只是起到存储key-value格式数据对的作用，下标对应的是key，数据是value。

**Comment by voidii** [comment]
并没有读懂你的意思。。

**Comment by ShuaiHuang** [comment]
> 并没有读懂你的意思。。

读完数据结构再回头看看我说的什么意思。

**Comment by voidii** [comment]
哦我差不多明白了

**Comment by voidii** [comment]
哎我发现我语文真的越来越不行了
